//
//  FYIViewModel.swift
//  Swise
//
//  Created by Agfid Prasetyo on 26/07/23.
//

import Foundation

class FYIViewModel {
    var fyi = [
        FYIModel(title: "What Is BMI?", shortDesc: "You’ve heard this many times, but what is actually this about? Find out more here!", image: "", desc: [TextModel(content: "BMI stands for Body Mass Index. It is a numerical value calculated from a person's weight and height, and it is used to determine if someone is underweight, normal weight, overweight, or obese. The BMI formula is as follows:", styling: "none"), TextModel(content: "\n", styling: "none"), TextModel(content: "BMI = weight (kg) / height^2 (m^2)", styling: "none"), TextModel(content: "Where:", styling: "none"), TextModel(content: "Weight is measured in kilograms (kg).", styling: "bullet"), TextModel(content: "Height is measured in meters (m).", styling: "bullet"), TextModel(content: "\n", styling: "none"), TextModel(content: "To calculate your BMI, you divide your weight in kilograms by your height squared in meters. The result will give you your BMI value. The interpretation of BMI values is generally as follows:", styling: "none"), TextModel(content: "\n", styling: "none"), TextModel(content: "BMI less than 18.5: Underweight", styling: "bullet"), TextModel(content: "BMI between 18.5 and 24.9: Normal weight", styling: "bullet"), TextModel(content: "BMI between 25 and 29.9: Overweight", styling: "bullet"), TextModel(content: "BMI of 30 or higher: Obese", styling: "bullet"), TextModel(content: "\n", styling: "none"), TextModel(content: "It's essential to note that while BMI can provide a general indication of body fat levels, it does not consider other factors like muscle mass or body composition. Therefore, it may not be a perfect measure of an individual's overall health or fitness level. For a more accurate assessment of health, it's essential to consider other factors and consult with a healthcare professional.", styling: "none")]),
        FYIModel(title: " How to count my sugar intake?", shortDesc: "Find out more here!", image: "", desc: [TextModel(content: "WHO recommends a reduced intake of free sugars throughout the lifecourse (strong recommendation1).", styling: "none"), TextModel(content: "In both adults and children, WHO recommends reducing the intake of free sugars to less than 10% of total energy intake2 (strong recommendation).", styling: "bullet"), TextModel(content: "WHO suggests a further reduction of the intake of free sugars to below 5% of total energy intake (conditional recommendation3).", styling: "bullet"), TextModel(content: "Free sugars include monosaccharides and disaccharides added to foods and beverages by the manufacturer, cook or consumer, and sugars naturally present in honey, syrups, fruit juices and fruit juice concentrates.", styling: "none"), TextModel(content: "\n", styling: "none"), TextModel(content: "Monitoring sugar intake requires awareness of its sources in your diet and tracking the amount consumed. Follow these steps to count your sugar intake:", styling: "none"), TextModel(content: "Read food labels: Check 'Total Sugars' in grams, including natural and added sugars.", styling: "1"), TextModel(content: "Identify hidden sugars: Look for words like sucrose, glucose, fructose, etc.", styling: "2"), TextModel(content: "Mind serving sizes: Multiply sugar content if consuming multiple servings.", styling: "3"), TextModel(content: "Use apps or food journals: Scan barcodes for instant nutritional info.", styling: "4"), TextModel(content: "Monitor sugar in beverages: Cut back on sugary drinks like soda and fruit juices.", styling: "5"), TextModel(content: "Track fruit intake: Balance natural sugar sources with other food groups.", styling: "6"), TextModel(content: "Be cautious with condiments: Read labels and use sugary sauces sparingly.", styling: "7"), TextModel(content: "Reduce processed snacks: Opt for healthier options like nuts and fresh fruits.", styling: "8"), TextModel(content: "Cook at home: Control sugar content, use natural sweeteners in moderation.", styling: "9"), TextModel(content: "Be consistent: Track sugar intake regularly for healthier choices.", styling: "10"), TextModel(content: "By following these steps, you can reduce the risk of health issues linked to excessive sugar consumption.", styling: "none")])
    ]
}
